routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/instaporn', 'AppController@index')->name('instaporn');
Route::get('/instaporn/download', 'AppController@download')->name('instaporn_download');
//Route::get('/instaporn/{category}', 'AppController@category');
//Route::get('/instaporn/{category}/{subcategory}', 'AppController@category');
Route::get('/instaporn/{category}/{subcategory?}/{subsubcategory?}', 'AppController@category')->name('instaporn-category');
Route::get('/image/{id}', 'AppController@image')->name('image');
//Route::get('/category/{id}', 'AppController@category')->name('image-category');

Auth::routes(['verify' => true]);

// admin-lte
Route::prefix( '/admin' )->group( function () {

    Route::get('/admin-lte/{locale}', 'Admin\AdminController@setLang')->name('lang');
    Route::get('/', 'Admin\AdminController@index')->name('dashboard');

    Route::resource('/users','Admin\UserController');
    Route::resource('/countries','Admin\CountryController');
    Route::resource('/cities','Admin\CityController');

    // file manager
    Route::get('/filemanager','Admin\FilemanagerController@index')->name('filemanager');
    Route::get('/filemanager/show','Admin\FilemanagerController@show')->name('show-filemanager');
    Route::post('/filemanager/upload','Admin\FilemanagerController@upload')->name('upload-items');
    Route::post('/filemanager/new','Admin\FilemanagerController@folder')->name('new-folder');
    Route::post('/filemanager/delete','Admin\FilemanagerController@delete')->name('delete-items');

    //Settings
    Route::resource('/generalSettings','Admin\GeneralSettingController');

    //Categories for images
    Route::post('/category/multidelete','Admin\CategoryController@multidelete')->name('category.multi-delete');
    Route::get('/category/packet','Admin\CategoryController@packet')->name('category.new-packet');
    Route::post('/category/packet','Admin\CategoryController@packet')->name('category.create-packet');
    Route::resource('/category','Admin\CategoryController');

    Route::any('/images/category/{id}','Admin\ImageController@category')->name('admin.image.by-category');
    Route::any('/images/delete','Admin\ImageController@delete')->name('images.delete');
    Route::resource('/images','Admin\ImageController');

    Route::get('/google-search/search','Admin\GSearchController@search')->name('google-search.search');
    Route::post('/google-search/search','Admin\GSearchController@search')->name('google-search.search');
    Route::post('/google-search','Admin\GSearchController@store')->name('google-search.store');

    Route::resource('/google-search','Admin\GSearchController');

});

app/Http/Controllers/Admin/ImageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Jobs\ImageThumbnail;
use App\Models\Category;
use App\Models\Image;
use App\Models\ImageCategory;
use App\Models\ImageDB;
use App\Models\ImageTool;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

/**
 * Are you idiot or what? Why did you extend AdminControlers from Controller?
 * Really?
 * You can look to another controllers and you can see whole
 * controler in admin groups extends from AdminController
 */
class ImageController extends Controller
{
    public function __construct()
    {
        $this->middleware('hasPermission:admin');
        parent::__construct();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $images = ImageDB::whereNotNull('id')->paginate($this->paginate);
        return view('admin.images.index', [
            'images'=>$images,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $image = new ImageDB();
        $categories_global = Category::whereIn('id',Category::GLOBAL_CATEGORIES)->pluck('title','title');
        return view('admin.images.create', [
            'image'=>$image,
            'categories_global'=>$categories_global,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $files = $request->file('images');
        $categories = Category::whereIn('id',$data['category'])->with('parent')->get();

        foreach ($files as $image)
        {
            $name = $image->getClientOriginalName();
            $path = $image->store('public/images/catalog/');

            $file_info = pathinfo(storage_path('app/'.$path));

            $thumbnail = $path; //TODO make resize

            $imagedb = ImageDB::create([
                'title' => $name,
                'path' => $path,
                'thumbnail' => $thumbnail,
                'created_by' => $data['created_by'],
            ]);
            $type = strtolower($file_info['extension']);
            if ($type == 'gif')
            {
                $imagedb->type = 'gif';
            }
            $imagedb->save();

            ImageThumbnail::dispatch($imagedb);

            foreach ($categories as $category)
            {
                $image_category = ImageCategory::create([
                    'image_id' => $imagedb->id,
                    'category_id' => $category->id,
                ]);
                $image_category->save();
            }
        }
        return redirect()
            ->route('images.index')
            ->with( 'message.level', 'success' )
            ->with( 'message.content', __('general.create_success') );

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        return redirect()
            ->route('images.index')
            ->with( 'message.level', 'success' )
            ->with( 'message.content', 'SHOW'.$id );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        return redirect()
            ->route('images.index')
            ->with( 'message.level', 'success' )
            ->with( 'message.content', 'EDIT'.$id );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        return redirect()
            ->route('images.index')
            ->with( 'message.level', 'success' )
            ->with( 'message.content', 'UPDATE'.$id );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(ImageDB $image)
    {
//        dd($image);
        Storage::delete($image->path);

        $image->delete();
        return redirect()
            ->back()
            ->with( 'message.level', 'success' )
            ->with( 'message.content', __('general.delete_success') );
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete(Request $request)
    {
        $data = $request->all();
        $images = ImageDB::whereIn('id',json_decode($data['ids']))->get();
        foreach ($images as $image)
        {
            Storage::delete($image->path);
            $image->delete();
        }

        return redirect()
            ->back()
            ->with( 'message.level', 'success' )
            ->with( 'message.content', __('general.delete_success') );
    }

    public function category($id)
    {
        $imgIds = ImageCategory::where('category_id',$id)->pluck('image_id');
//        dd($imgIds);
        $images = ImageDB::whereIn('id',$imgIds)->paginate(10);
        $category = Category::where('id',$id)->first();
        return view('admin.images.index', [
            'images'=>$images,
            'category'=>$category,
        ]);
    }
}

resources/views/admin/images/create.blade.php
@extends('admin.layouts.admin-lte')

@section('title', __('general.images'))
@section('content-title', __('general.images'))

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> {{ __('general.dashboard') }}</a></li>
        <li><a href="{{ route('images.index') }}"><i class="fa fa-building"></i> {{ __('general.images') }}</a></li>
        <li class="active"><i class="fa fa-building"></i> {{ __('general.new') }}</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            {!! Form::open(['route' => 'images.store','method' => 'post','files' => true]) !!}
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ __('general.images_creating') }}</h3>
                    <div class="pull-right">
                        {!! Form::submit(__('general.save'), ['class' => 'btn btn-success']) !!}

                        <a href="{{ route('images.index') }}" class="btn btn-default"><i class="fa fa-share"></i></a>
                    </div>
                </div>
                <div class="box-body">

                    @include('admin.images.partials.form')

                    {!! Form::hidden('created_by', Auth::id()) !!}
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/images/edit.blade.php
@extends('admin.layouts.admin-lte')

@section('title', __('general.category'))
@section('content-title', __('general.category'))

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> {{ __('general.dashboard') }}</a></li>
        <li><a href="{{ route('category.index') }}"><i class="fa fa-building"></i> {{ __('general.category') }}</a></li>
        <li class="active"><i class="fa fa-building"></i> {{ __('general.edit') }}</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            {!! Form::model($category, ['route' => ['category.update', $category],'method' => 'put','files' => true]) !!}
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ __('general.category_edit') }}</h3>
                    <div class="pull-right">
                        {!! Form::submit(__('general.save'), ['class' => 'btn btn-success']) !!}

                        <a href="{{ route('category.index') }}" class="btn btn-default"><i class="fa fa-share"></i></a>
                    </div>
                </div>
                <div class="box-body">
                    {!! Form::hidden('id', $category->id) !!}
                    @include('admin.category.partials.form')
                    {!! Form::hidden('modified_by', Auth::id()) !!}
                </div>

            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/images/index.blade.php
@extends('admin.layouts.admin-lte')

@section('title', __('general.images'))
@section('content-title', __('general.images'))

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <form action="{{route('images.delete')}}" method="POST">
            <div class="box box-primary">
                <div class="box-header with-border row-no-gutters">
                    <div class="pull-left col row-no-gutters">
                        {!! \App\Models\Category::adminnavigation() !!}
                        {{--<form onsubmit="if(confirm('{{ __('general.deleting') }}')){ return true }else{ return false }" action="{{ route('category.multi-delete') }}" method="post">--}}
                            {{--<input type="hidden" name="_method" value="delete" />--}}
                            {{--<input id="ids-to-delete" type="hidden" name="ids" value="" />--}}
                            {{--{{csrf_field()}}--}}
                            {{--<button type="submit" class="btn-sm remove_item btn btn-danger pull-left"><i class="fa fa-trash"></i></button>--}}
                        {{--</form>--}}
                    </div>
                    <div class="pull-right col">
                        <button class="btn btn-danger btn-sm" type="submit" onclick="idstodelete();"><i class="fa fa-trash"></i> Delete selected</button>
                        <input hidden id="ids-to-delete" name="ids">
                        <a href="{{ route('images.create') }}" class="btn btn-sm btn-success add_new_product">
                            {{ __('general.new') }}
                        </a>
                        {{--<a href="{{ route('image.new-packet') }}" class="btn btn-sm btn-success add_new_product">--}}
                            {{--{{ __('general.category_packet') }}--}}
                        {{--</a>--}}

                        {{--<a href="" id="categories_file" data-toggle="image" class="btn btn-sm btn-success add_new_product">--}}
                            {{--<img src="" alt="" title="" data-placeholder="test">--}}
                        {{--</a>--}}
                        {{--<input type="hidden" name="categories_file" value="" id="categories_file">--}}
                    </div>
                </div>
                <div class="box-body">

                    <div class="row-no-gutters">
                            <ul class="grid">
                                @foreach($images as $image)

                                    <li class="grid-item">
                                        <div class="grid-item-wrapper">

                                            <span class="mailbox-attachment-icon has-img">
                                                <a href="/{{ $image->src() }}" data-fancybox>
                                                    <img src="/{{ $image->src() }}" alt="Attachment">
                                                </a>
                                            </span>

                                            <div class="mailbox-attachment-info">
                                                <p class="mailbox-attachment-name">
                                                    <input type="checkbox" id="id" value="{{ $image->id }}" onclick="idstodelete();">
                                                    <i class="fa fa-camera"></i>
                                                    {{ $image->title }}
                                                </p>

                                                <span class="mailbox-attachment-size flex-reverse-custom">
                                                    <a href="/{{ $image->src() }}" class="btn btn-primary btn-xs pull-right">
                                                        <i class="fa fa-cloud-download"></i>
                                                    </a>

                                                    @foreach($image->categories as $category)
                                                        <small>{{ $category->title }}</small>
                                                    @endforeach

                                                    @include('admin.images.partials.formdelete')
                                                </span>
                                            </div>
                                        </div>
                                    </li>
                                @endforeach

                            </ul>
                    </div>

                    <nav aria-label="page navigation">
                        <ul class="pagination">
                            {{$images->links()}}
                        </ul>
                    </nav>
                </div>
            </div>
            </form>
        </div>
    </div>
    <script>
        function idstodelete(){
            var ids = [];
            $('input#id').each(function () {
                $(this).prop('checked') ? ids.push($(this).val()) : null;
            });
            console.log(JSON.stringify(ids));
            $('input#ids-to-delete').val(JSON.stringify(ids));
        }
    </script>
@endsection