routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/instaporn', 'AppController@index')->name('instaporn');
Route::get('/instaporn/download', 'AppController@download')->name('instaporn_download');
//Route::get('/instaporn/{category}', 'AppController@category');
//Route::get('/instaporn/{category}/{subcategory}', 'AppController@category');
Route::get('/instaporn/{category}/{subcategory?}/{subsubcategory?}', 'AppController@category')->name('instaporn-category');
Route::get('/image/{id}', 'AppController@image')->name('image');
//Route::get('/category/{id}', 'AppController@category')->name('image-category');

Auth::routes(['verify' => true]);

// admin-lte
Route::prefix( '/admin' )->group( function () {

    Route::get('/admin-lte/{locale}', 'Admin\AdminController@setLang')->name('lang');
    Route::get('/', 'Admin\AdminController@index')->name('dashboard');

    Route::resource('/users','Admin\UserController');
    Route::resource('/countries','Admin\CountryController');
    Route::resource('/cities','Admin\CityController');

    // file manager
    Route::get('/filemanager','Admin\FilemanagerController@index')->name('filemanager');
    Route::get('/filemanager/show','Admin\FilemanagerController@show')->name('show-filemanager');
    Route::post('/filemanager/upload','Admin\FilemanagerController@upload')->name('upload-items');
    Route::post('/filemanager/new','Admin\FilemanagerController@folder')->name('new-folder');
    Route::post('/filemanager/delete','Admin\FilemanagerController@delete')->name('delete-items');

    //Settings
    Route::resource('/generalSettings','Admin\GeneralSettingController');

    //Categories for images
    Route::post('/category/multidelete','Admin\CategoryController@multidelete')->name('category.multi-delete');
    Route::get('/category/packet','Admin\CategoryController@packet')->name('category.new-packet');
    Route::post('/category/packet','Admin\CategoryController@packet')->name('category.create-packet');
    Route::resource('/category','Admin\CategoryController');

    Route::any('/images/category/{id}','Admin\ImageController@category')->name('admin.image.by-category');
    Route::any('/images/delete','Admin\ImageController@delete')->name('images.delete');
    Route::resource('/images','Admin\ImageController');

    Route::get('/google-search/search','Admin\GSearchController@search')->name('google-search.search');
    Route::post('/google-search/search','Admin\GSearchController@search')->name('google-search.search');
    Route::post('/google-search','Admin\GSearchController@store')->name('google-search.store');

    Route::resource('/google-search','Admin\GSearchController');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasRoles;
    use Notifiable;
    use SoftDeletes;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'phone', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }

    public function setEmailAttribute($email)
    {
        $this->attributes['email'] = strtolower($email);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\App;

//use App\Models\UserAvatar;
use Auth;

class UserController extends AdminController
{
    public function __construct()
    {
        $this->middleware('hasPermission:users');
        parent::__construct();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view( 'admin.user.index',
            [
                'users' => User::orderBy('name')->where('id','!=',Auth::id())->paginate($this->paginate)
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create',
            [
                'user' => [],
                'roles' => Role::get(),
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::create($request->except('avatar_id'));
        $roles  = $request['roles'];
//        if($request->has('avatar_id' )){
//            $avatar = UserAvatar::where('id', $request->input('avatar_id'))->first();
//            if(isset($avatar)) {
//                $avatar->user_id = $user->id;
//                $avatar->save();
//            }
//        }

        //Checking if a role was selected
        if (isset($roles)) {
            foreach ($roles as $role) {
                $role_r = Role::where( 'id', '=', $role )->firstOrFail();
                $user->assignRole($role_r);
            }
        }
        $user->save();
        return redirect()
            ->route( 'users.index' )
            ->with( 'message.level', 'success' )
            ->with( 'message.content', 'User successfully added.' );
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return redirect()->route('users.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user) {
        $roles = Role::get();

        $user = User::select( [ 'id','name','email','phone',] )
            ->where( 'id', $user->id )
            ->firstOrFail();

        return view( 'admin.user.edit', [
            'user'      => $user,
            'roles'     => $roles,
        ] );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->update($request->except('avatar_id','password'));
//        if($request->has('avatar_id' )){
//            $avatar = UserAvatar::where('id', $request->input('avatar_id'))->first();
//            if(!is_null($avatar)) {
//                $avatar->user_id = $user->id;
//                $avatar->save();
//            }else{
//                $user->avatar_id = null;
//            }
//        }

        if (!$request['password'] == '' ) {
            $input['password'] = $request['password'];
        }

        $user->save();

        $roles = $request['roles'];
        if (isset($roles)) {
            $user->roles()->detach();
            foreach ($roles as $role) {
                $role_r = Role::where( 'id', '=', $role )->firstOrFail();
                $user->assignRole( $role_r );
            }
        }

        return redirect()
            ->route( 'users.index' )
            ->with( 'message.level', 'success' )
            ->with( 'message.content', 'User successfully updated.' );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()
            ->route( 'users.index' )
            ->with( 'message.level', 'success' )
            ->with( 'message.content', 'User successfully deleted.' );
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.admin-lte')

@section('title', __('general.users'))
@section('content-title', __('general.users'))

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> {{ __('general.dashboard') }}</a></li>
        <li><a href="{{ route('users.index') }}"><i class="fa fa-thumbs-up"></i> {{ __('general.users') }}</a></li>
        <li class="active"><i class="fa fa-thumbs-up"></i> {{ __('general.edit') }}</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            {!! Form::open(['route' => 'users.store','method' => 'post','files' => true]) !!}
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ __('general.user_creating') }}</h3>
                    <div class="pull-right">
                        {!! Form::submit(__('general.save'), ['class' => 'btn btn-success']) !!}

                        <a href="{{ route('users.index') }}" class="btn btn-default"><i class="fa fa-share"></i></a>
                    </div>
                </div>
                <div class="box-body">

                    @include('admin.user.partials.form')

                    {!! Form::hidden('created_by', Auth::id()) !!}
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(function () {

            function randString(id){
                var dataSet = $(id).attr('data-character-set').split(',');
                var possible = '';
                if($.inArray('a-z', dataSet) >= 0){
                    possible += 'abcdefghijklmnopqrstuvwxyz';
                }
                if($.inArray('A-Z', dataSet) >= 0){
                    possible += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
                }
                if($.inArray('0-9', dataSet) >= 0){
                    possible += '0123456789';
                }
                if($.inArray('#', dataSet) >= 0){
                    possible += '![]{}()%&*$#^<>~@|';
                }
                var text = '';
                for(var i=0; i < $(id).attr('data-size'); i++) {
                    text += possible.charAt(Math.floor(Math.random() * possible.length));
                }
                return text;
            }

            // Create a new password
            $(".getNewPass").click(function(){
                var field = $(this).closest('div').find('input[rel="gp"]');
                var password = randString(field);
                field.val(password).prop("type", "text");
                $('input[rel="gp_confirm"]').val(password).prop("type", "text");
            });

            // Auto Select Pass On Focus
            $('input[rel="gp"]').on("click", function () {
                $(this).select();
            });


        });
    </script>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.admin-lte')

@section('title', __('general.users'))
@section('content-title', __('general.users'))


@section('breadcrumbs')
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> {{ __('general.dashboard') }}</a></li>
        <li><a href="{{ route('users.index') }}"><i class="fa fa-star"></i> {{ __('general.users') }}</a></li>
        <li class="active"><i class="fa fa-star"></i> {{ __('general.edit') }}</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ __('general.edit') }}</h3>
                    <div class="pull-right">
                        {!! Form::submit(__('general.save'), ['class' => 'btn btn-success', 'form' => 'user_create_form']) !!}

                        <a href="{{ route('users.index') }}" class="btn btn-default"><i class="fa fa fa-share"></i></a>

                    </div>
                </div>
                {!! Form::model($user, ['route' => ['users.update', $user],'method' => 'put','files' => true, 'id' => 'user_create_form']) !!}
                <div class="box-body">
                    @include('admin.user.partials.form')
                    {!! Form::hidden('modified_by', Auth::id()) !!}
                </div>

            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(function () {

            function randString(id){
                var dataSet = $(id).attr('data-character-set').split(',');
                var possible = '';
                if($.inArray('a-z', dataSet) >= 0){
                    possible += 'abcdefghijklmnopqrstuvwxyz';
                }
                if($.inArray('A-Z', dataSet) >= 0){
                    possible += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
                }
                if($.inArray('0-9', dataSet) >= 0){
                    possible += '0123456789';
                }
                if($.inArray('#', dataSet) >= 0){
                    possible += '![]{}()%&*$#^<>~@|';
                }
                var text = '';
                for(var i=0; i < $(id).attr('data-size'); i++) {
                    text += possible.charAt(Math.floor(Math.random() * possible.length));
                }
                return text;
            }

            // Create a new password
            $(".getNewPass").click(function(){
                var field = $(this).closest('div').find('input[rel="gp"]');
                var password = randString(field);
                field.val(password).prop("type", "text");
                $('input[rel="gp_confirm"]').val(password).prop("type", "text");
            });

            // Auto Select Pass On Focus
            $('input[rel="gp"]').on("click", function () {
                $(this).select();
            });


        });
    </script>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.admin-lte')

@section('title', __('general.users_list'))
@section('content-title', __('general.users_list'))

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> {{ __('general.dashboard') }}</a></li>
        <li class="active"><i class="fa fa-thumbs-up"></i>{{ __('general.users') }}</li>
    </ol>
@endsection

@section('content')
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">{{ __('general.users') }}</h3>
        <div class="pull-right">
            <a href="{{ route('users.create') }}" class="btn btn-sm btn-success add_new_user">
                {{ __('general.new') }}
            </a>
        </div>
    </div>
    <div class="box-body">
        <table class="table table-hover table-striped table-bordered table-condensed">
            <thead>
            <tr>
                <th>{{ __('general.user') }}</th>
                <th>{{ __('general.email') }}</th>
                <th>{{ __('general.users_roles') }}</th>
                <th>
                </th>
            </tr>
            </thead>
            <tbody>
            @forelse($users as $user)
                <tr>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->roles()->pluck('name')->implode(', ') }}</td>
                    <td class="td-action">
                        <a href="{{ route('users.edit', $user) }}" class="btn btn-success btn-sm pull-left">
                            <i class="fa fa-pencil"></i>
                        </a>

                        <form onsubmit="if(confirm('{{ __('general.deleting') }}')){ return true }else{ return false }" action="{{ route('users.destroy', $user) }}" method="post">
                            <input type="hidden" name="_method" value="delete" />
                            {{csrf_field()}}
                            <button type="submit" class="btn-sm remove_item btn btn-danger pull-left"><i class="fa fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td><h2>{{ __('general.empty_data') }}</h2></td>
                </tr>
            @endforelse
            </tbody>
        </table>
        <nav aria-label="page navigation">
            <ul class="pagination">
                {{$users->links()}}
            </ul>
        </nav>
    </div>
</div>
@endsection

@section('js')
    <script>
        $(function () {
            $('#users_list').DataTable({
                "aoColumnDefs": [
                    {"bSortable": false, "aTargets": [3, 4]}
                ]
            });
        });
    </script>
@endsection

resources/views/admin/user/profile.blade.php
@extends('admin.layouts.admin-lte')

@section('title', __('general.profile'))
@section('content-title', __('general.profile'))

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> {{ __('dashboard.dashboard') }}</a></li>
        <li class="active"><i class="fa fa-user"></i> {{ __('general.edit') }} {{$user->name}}</li>
    </ol>
@endsection

@section('content')
    <script>
        $(document).ready(function(){
            $('#avatar').on('change', function(){
                var fd = new FormData();
                $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
                fd.append('user_id', $('#user_id').val());
                fd.append('avatar', this.files[0]);
                $.ajax({
                    type: 'POST',
                    url: '{{route("uploadAvatar")}}',
                    data: fd,
                    processData: false,
                    contentType: false,
                    dataType: "json",
                    success: function(response){
                        console.log('Response:', response);
                        $('#avatar-id').val(response.avatar.id);
                        $('#user-avatar').attr('src', response.avatar.url);
                        $('#avatar-name').val(response.avatar.name);
                        $('#avatar-path').val(response.avatar.path);

                        var btn = $('#user-avatar-remove');
                        btn.val(response.avatar.id);
                        if(btn.hasClass('hidden')) {
                            btn.removeClass('hidden');
                        }
                    },
                    error: function(response) {

                    }
                });
            });

            $('#user-avatar-remove').on('click', function() {
                $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
                $.ajax({
                    type: 'POST',
                    url: '{{route("removeAvatar")}}',
                    data: {'avatar_id': $('#user-avatar-remove').val()},
                    dataType: "json",
                    success: function(response) {
                        console.log('Response:', response);
                        $('#avatar-id').val('');
                        $('#user-avatar').attr('src', response.url);
                        $('#avatar-name').val('');
                        $('#avatar-path').val('');

                        var btn = $('#user-avatar-remove');
                        btn.val('');
                        if(!btn.hasClass('hidden')) {
                            btn.addClass('hidden');
                        }
                    }
                });
            });

        });
    </script>


    <div class="box">
        <div class="box-body">
            {{ Form::model($user, [
                'route' => array('profile.save'),
                'method' => 'PUT',
                'id' => 'edit_form'
            ]) }}

            <div class="col-xl-4">
                @if(isset($user->avatar->path))
                    <img src="{{ Storage::url($user->avatar->path) }}" id="user-avatar" alt="user-avatar" style="width: 10%">
                @else
                    <img src="{{ Storage::url('public/users/avatars/user.png') }}" id="user-avatar" alt="user-avatar" style="width: 10%">
                @endif
            </div>

            <label for="file">Choose file to upload</label>
            <input type="file" name="avatar" class="avatar" id="avatar" />

            @if(is_null($user->avatar_id))
                <button class="hidden btn btn-flat" id="user-avatar-remove" value="{{$user->avatar_id or ''}}">
                    <i class="fa fa-remove"></i>
                </button>
            @else
                <button class="btn btn-flat" id="user-avatar-remove" value="{{$user->avatar_id or ''}}">
                    <i class="fa fa-remove"></i>
                </button>
            @endif

            <input type="hidden" name="user_id" id="user_id" value="{{ $user->id }}">
            <input type="hidden" name="avatar_id" id="avatar-id" value="@if(old('avatar_id')){{old('avatar_id')}}@else{{$user->avatar_id or ''}}@endif">
            <input type="hidden" name="avatar_name" id="avatar-name" value="">
            <input type="hidden" name="avatar_path" id="avatar-path" value="">


            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                {{ Form::label('name', __('general.name')) }}
                {{ Form::text('name', null, array('class' => 'form-control')) }}
                @if ($errors->has('name'))
                    <span class="help-block">{{ $errors->first('name') }}</span>
                @endif
            </div>

            <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                {{ Form::label('email', __('general.email')) }}
                {{ Form::email('email', null, array('class' => 'form-control')) }}
                @if ($errors->has('email'))
                    <span class="help-block">{{ $errors->first('email') }}</span>
                @endif
            </div>

            <div class="alert fa-border alert-dismissible">

            <h4><i class="icon fa fa-info"></i> {{ __('general.password_unchanged') }}</h4>
            <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                {{ Form::label('password', __('general.password')) }}<br>
                {{ Form::password('password', array('class' => 'form-control')) }}
                @if ($errors->has('password'))
                    <span class="help-block">{{ $errors->first('password') }}</span>
                @endif
            </div>

            <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
                {{ Form::label('password', __('general.password_confirm')) }}<br>
                {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
                @if ($errors->has('password_confirmation'))
                    <span class="help-block">{{ $errors->first('password_confirmation') }}</span>
                @endif
            </div>
            </div>
            {{ Form::submit(__('general.save'), array('class' => 'btn btn-primary')) }}

            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(function() {
            $('#edit_form').submit(function(){
                $('#edit_form :password').each(function(){
                    if($(this).val() == '') {
                        $(this).attr("disabled", "disabled")
                    }
                });
            })
        });
    </script>
@endsection